"""create tables

Revision ID: 8326f43d1c27
Revises: 
Create Date: 2022-01-23 02:56:39.921151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8326f43d1c27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('name_en', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pickups',
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('display_id', sa.String(length=128), nullable=True),
    sa.Column('test_id', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), server_default='0', nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_id'),
    sa.UniqueConstraint('test_id')
    )
    op.create_table('announces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('title_en', sa.String(length=128), nullable=True),
    sa.Column('artists', sa.String(length=128), nullable=True),
    sa.Column('artists_en', sa.String(length=128), nullable=True),
    sa.Column('author', sa.String(length=128), nullable=True),
    sa.Column('author_en', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('description_en', sa.String(length=512), nullable=True),
    sa.Column('public', sa.Boolean(), server_default='0', nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('coverHash', sa.String(length=128), nullable=True),
    sa.Column('bgmHash', sa.String(length=128), nullable=True),
    sa.Column('dataHash', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backgrounds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('title_en', sa.String(length=128), nullable=True),
    sa.Column('artists', sa.String(length=128), nullable=True),
    sa.Column('artists_en', sa.String(length=128), nullable=True),
    sa.Column('author', sa.String(length=128), nullable=True),
    sa.Column('author_en', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('description_en', sa.String(length=512), nullable=True),
    sa.Column('public', sa.Boolean(), server_default='0', nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('thumbnailHash', sa.String(length=128), nullable=True),
    sa.Column('dataHash', sa.String(length=128), nullable=True),
    sa.Column('imageHash', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('effects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('title_en', sa.String(length=128), nullable=True),
    sa.Column('artists', sa.String(length=128), nullable=True),
    sa.Column('artists_en', sa.String(length=128), nullable=True),
    sa.Column('author', sa.String(length=128), nullable=True),
    sa.Column('author_en', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('description_en', sa.String(length=512), nullable=True),
    sa.Column('public', sa.Boolean(), server_default='0', nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('thumbnailHash', sa.String(length=128), nullable=True),
    sa.Column('dataHash', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('particles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('title_en', sa.String(length=128), nullable=True),
    sa.Column('artists', sa.String(length=128), nullable=True),
    sa.Column('artists_en', sa.String(length=128), nullable=True),
    sa.Column('author', sa.String(length=128), nullable=True),
    sa.Column('author_en', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('description_en', sa.String(length=512), nullable=True),
    sa.Column('public', sa.Boolean(), server_default='0', nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('thumbnailHash', sa.String(length=128), nullable=True),
    sa.Column('dataHash', sa.String(length=128), nullable=True),
    sa.Column('textureHash', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('title_en', sa.String(length=128), nullable=True),
    sa.Column('artists', sa.String(length=128), nullable=True),
    sa.Column('artists_en', sa.String(length=128), nullable=True),
    sa.Column('author', sa.String(length=128), nullable=True),
    sa.Column('author_en', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('description_en', sa.String(length=512), nullable=True),
    sa.Column('public', sa.Boolean(), server_default='0', nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('thumbnailHash', sa.String(length=128), nullable=True),
    sa.Column('dataHash', sa.String(length=128), nullable=True),
    sa.Column('textureHash', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('title_en', sa.String(length=128), nullable=True),
    sa.Column('artists', sa.String(length=128), nullable=True),
    sa.Column('artists_en', sa.String(length=128), nullable=True),
    sa.Column('author', sa.String(length=128), nullable=True),
    sa.Column('author_en', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('description_en', sa.String(length=512), nullable=True),
    sa.Column('public', sa.Boolean(), server_default='0', nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('thumbnailHash', sa.String(length=128), nullable=True),
    sa.Column('dataHash', sa.String(length=128), nullable=True),
    sa.Column('configurationHash', sa.String(length=128), nullable=True),
    sa.Column('background_id', sa.Integer(), nullable=True),
    sa.Column('effect_id', sa.Integer(), nullable=True),
    sa.Column('particle_id', sa.Integer(), nullable=True),
    sa.Column('skin_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['background_id'], ['backgrounds.id'], ),
    sa.ForeignKeyConstraint(['effect_id'], ['effects.id'], ),
    sa.ForeignKeyConstraint(['particle_id'], ['particles.id'], ),
    sa.ForeignKeyConstraint(['skin_id'], ['skins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('levels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('title_en', sa.String(length=128), nullable=True),
    sa.Column('artists', sa.String(length=128), nullable=True),
    sa.Column('artists_en', sa.String(length=128), nullable=True),
    sa.Column('author', sa.String(length=128), nullable=True),
    sa.Column('author_en', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('description_en', sa.String(length=512), nullable=True),
    sa.Column('public', sa.Boolean(), server_default='0', nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('bpm', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Integer(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('coverHash', sa.String(length=128), nullable=True),
    sa.Column('bgmHash', sa.String(length=128), nullable=True),
    sa.Column('dataHash', sa.String(length=128), nullable=True),
    sa.Column('engine_id', sa.Integer(), nullable=True),
    sa.Column('background_id', sa.Integer(), nullable=True),
    sa.Column('effect_id', sa.Integer(), nullable=True),
    sa.Column('particle_id', sa.Integer(), nullable=True),
    sa.Column('skin_id', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.Column('pickup_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['background_id'], ['backgrounds.id'], ),
    sa.ForeignKeyConstraint(['effect_id'], ['effects.id'], ),
    sa.ForeignKeyConstraint(['engine_id'], ['engines.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.ForeignKeyConstraint(['particle_id'], ['particles.id'], ),
    sa.ForeignKeyConstraint(['pickup_id'], ['pickups.id'], ),
    sa.ForeignKeyConstraint(['skin_id'], ['skins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('likes',
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    op.drop_table('favorites')
    op.drop_table('levels')
    op.drop_table('engines')
    op.drop_table('skins')
    op.drop_table('particles')
    op.drop_table('effects')
    op.drop_table('backgrounds')
    op.drop_table('announces')
    op.drop_table('users')
    op.drop_table('pickups')
    op.drop_table('genres')
    # ### end Alembic commands ###
