"""create all tables

Revision ID: 886ce6d09526
Revises:
Create Date: 2022-01-28 08:27:58.855439

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "886ce6d09526"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "genres",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("nameEn", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("createdTime", sa.Integer(), nullable=True),
        sa.Column("updatedTime", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("userId", sa.String(length=128), nullable=True),
        sa.Column("testId", sa.String(length=128), nullable=True),
        sa.Column("accountId", sa.String(length=128), nullable=True),
        sa.Column("isAdmin", sa.Boolean(), server_default="0", nullable=True),
        sa.Column("isDeleted", sa.Boolean(), server_default="0", nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("accountId"),
        sa.UniqueConstraint("testId"),
        sa.UniqueConstraint("userId"),
    )
    op.create_table(
        "announces",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("title", sa.String(length=128), nullable=True),
        sa.Column("titleEn", sa.String(length=128), nullable=True),
        sa.Column("artists", sa.String(length=128), nullable=True),
        sa.Column("artistsEn", sa.String(length=128), nullable=True),
        sa.Column("author", sa.String(length=128), nullable=True),
        sa.Column("authorEn", sa.String(length=128), nullable=True),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column("descriptionEn", sa.String(length=512), nullable=True),
        sa.Column("public", sa.Boolean(), server_default="0", nullable=True),
        sa.Column("createdTime", sa.Integer(), nullable=True),
        sa.Column("updatedTime", sa.Integer(), nullable=True),
        sa.Column("coverHash", sa.String(length=128), nullable=True),
        sa.Column("bgmHash", sa.String(length=128), nullable=True),
        sa.Column("dataHash", sa.String(length=128), nullable=True),
        sa.Column("userId", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "backgrounds",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("title", sa.String(length=128), nullable=True),
        sa.Column("titleEn", sa.String(length=128), nullable=True),
        sa.Column("artists", sa.String(length=128), nullable=True),
        sa.Column("artistsEn", sa.String(length=128), nullable=True),
        sa.Column("author", sa.String(length=128), nullable=True),
        sa.Column("authorEn", sa.String(length=128), nullable=True),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column("descriptionEn", sa.String(length=512), nullable=True),
        sa.Column("public", sa.Boolean(), server_default="0", nullable=True),
        sa.Column("createdTime", sa.Integer(), nullable=True),
        sa.Column("updatedTime", sa.Integer(), nullable=True),
        sa.Column("thumbnailHash", sa.String(length=128), nullable=True),
        sa.Column("dataHash", sa.String(length=128), nullable=True),
        sa.Column("imageHash", sa.String(length=128), nullable=True),
        sa.Column("userId", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "effects",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("title", sa.String(length=128), nullable=True),
        sa.Column("titleEn", sa.String(length=128), nullable=True),
        sa.Column("artists", sa.String(length=128), nullable=True),
        sa.Column("artistsEn", sa.String(length=128), nullable=True),
        sa.Column("author", sa.String(length=128), nullable=True),
        sa.Column("authorEn", sa.String(length=128), nullable=True),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column("descriptionEn", sa.String(length=512), nullable=True),
        sa.Column("public", sa.Boolean(), server_default="0", nullable=True),
        sa.Column("createdTime", sa.Integer(), nullable=True),
        sa.Column("updatedTime", sa.Integer(), nullable=True),
        sa.Column("thumbnailHash", sa.String(length=128), nullable=True),
        sa.Column("dataHash", sa.String(length=128), nullable=True),
        sa.Column("userId", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "logs",
        sa.Column("createdTime", sa.Integer(), nullable=True),
        sa.Column("updatedTime", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("userId", sa.Integer(), nullable=True),
        sa.Column("type", sa.Integer(), nullable=True),
        sa.Column("param1", sa.String(length=16), nullable=True),
        sa.Column("param2", sa.String(length=16), nullable=True),
        sa.Column("param3", sa.String(length=16), nullable=True),
        sa.Column("raw", sa.String(length=512), nullable=True),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "particles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("title", sa.String(length=128), nullable=True),
        sa.Column("titleEn", sa.String(length=128), nullable=True),
        sa.Column("artists", sa.String(length=128), nullable=True),
        sa.Column("artistsEn", sa.String(length=128), nullable=True),
        sa.Column("author", sa.String(length=128), nullable=True),
        sa.Column("authorEn", sa.String(length=128), nullable=True),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column("descriptionEn", sa.String(length=512), nullable=True),
        sa.Column("public", sa.Boolean(), server_default="0", nullable=True),
        sa.Column("createdTime", sa.Integer(), nullable=True),
        sa.Column("updatedTime", sa.Integer(), nullable=True),
        sa.Column("thumbnailHash", sa.String(length=128), nullable=True),
        sa.Column("dataHash", sa.String(length=128), nullable=True),
        sa.Column("textureHash", sa.String(length=128), nullable=True),
        sa.Column("userId", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "skins",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("title", sa.String(length=128), nullable=True),
        sa.Column("titleEn", sa.String(length=128), nullable=True),
        sa.Column("artists", sa.String(length=128), nullable=True),
        sa.Column("artistsEn", sa.String(length=128), nullable=True),
        sa.Column("author", sa.String(length=128), nullable=True),
        sa.Column("authorEn", sa.String(length=128), nullable=True),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column("descriptionEn", sa.String(length=512), nullable=True),
        sa.Column("public", sa.Boolean(), server_default="0", nullable=True),
        sa.Column("createdTime", sa.Integer(), nullable=True),
        sa.Column("updatedTime", sa.Integer(), nullable=True),
        sa.Column("thumbnailHash", sa.String(length=128), nullable=True),
        sa.Column("dataHash", sa.String(length=128), nullable=True),
        sa.Column("textureHash", sa.String(length=128), nullable=True),
        sa.Column("userId", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "engines",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("title", sa.String(length=128), nullable=True),
        sa.Column("titleEn", sa.String(length=128), nullable=True),
        sa.Column("artists", sa.String(length=128), nullable=True),
        sa.Column("artistsEn", sa.String(length=128), nullable=True),
        sa.Column("author", sa.String(length=128), nullable=True),
        sa.Column("authorEn", sa.String(length=128), nullable=True),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column("descriptionEn", sa.String(length=512), nullable=True),
        sa.Column("public", sa.Boolean(), server_default="0", nullable=True),
        sa.Column("createdTime", sa.Integer(), nullable=True),
        sa.Column("updatedTime", sa.Integer(), nullable=True),
        sa.Column("thumbnailHash", sa.String(length=128), nullable=True),
        sa.Column("dataHash", sa.String(length=128), nullable=True),
        sa.Column("configurationHash", sa.String(length=128), nullable=True),
        sa.Column("backgroundId", sa.Integer(), nullable=True),
        sa.Column("effectId", sa.Integer(), nullable=True),
        sa.Column("particleId", sa.Integer(), nullable=True),
        sa.Column("skinId", sa.Integer(), nullable=True),
        sa.Column("userId", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["backgroundId"],
            ["backgrounds.id"],
        ),
        sa.ForeignKeyConstraint(
            ["effectId"],
            ["effects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["particleId"],
            ["particles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["skinId"],
            ["skins.id"],
        ),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "levels",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("title", sa.String(length=128), nullable=True),
        sa.Column("titleEn", sa.String(length=128), nullable=True),
        sa.Column("artists", sa.String(length=128), nullable=True),
        sa.Column("artistsEn", sa.String(length=128), nullable=True),
        sa.Column("author", sa.String(length=128), nullable=True),
        sa.Column("authorEn", sa.String(length=128), nullable=True),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column("descriptionEn", sa.String(length=512), nullable=True),
        sa.Column("public", sa.Boolean(), server_default="0", nullable=True),
        sa.Column("createdTime", sa.Integer(), nullable=True),
        sa.Column("updatedTime", sa.Integer(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("bpm", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Integer(), nullable=True),
        sa.Column("length", sa.Integer(), nullable=True),
        sa.Column("coverHash", sa.String(length=128), nullable=True),
        sa.Column("bgmHash", sa.String(length=128), nullable=True),
        sa.Column("dataHash", sa.String(length=128), nullable=True),
        sa.Column("engineId", sa.Integer(), nullable=True),
        sa.Column("backgroundId", sa.Integer(), nullable=True),
        sa.Column("effectId", sa.Integer(), nullable=True),
        sa.Column("particleId", sa.Integer(), nullable=True),
        sa.Column("skinId", sa.Integer(), nullable=True),
        sa.Column("genreId", sa.Integer(), nullable=True),
        sa.Column("userId", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["backgroundId"],
            ["backgrounds.id"],
        ),
        sa.ForeignKeyConstraint(
            ["effectId"],
            ["effects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["engineId"],
            ["engines.id"],
        ),
        sa.ForeignKeyConstraint(
            ["genreId"],
            ["genres.id"],
        ),
        sa.ForeignKeyConstraint(
            ["particleId"],
            ["particles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["skinId"],
            ["skins.id"],
        ),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "favorites",
        sa.Column("createdTime", sa.Integer(), nullable=True),
        sa.Column("updatedTime", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("userId", sa.Integer(), nullable=True),
        sa.Column("levelId", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["levelId"],
            ["levels.id"],
        ),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "likes",
        sa.Column("createdTime", sa.Integer(), nullable=True),
        sa.Column("updatedTime", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("userId", sa.Integer(), nullable=True),
        sa.Column("levelId", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["levelId"],
            ["levels.id"],
        ),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pickups",
        sa.Column("createdTime", sa.Integer(), nullable=True),
        sa.Column("updatedTime", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.Column("levelId", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["levelId"],
            ["levels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "votes",
        sa.Column("createdTime", sa.Integer(), nullable=True),
        sa.Column("updatedTime", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("userId", sa.Integer(), nullable=True),
        sa.Column("levelId", sa.Integer(), nullable=True),
        sa.Column("value", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["levelId"],
            ["levels.id"],
        ),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("votes")
    op.drop_table("pickups")
    op.drop_table("likes")
    op.drop_table("favorites")
    op.drop_table("levels")
    op.drop_table("engines")
    op.drop_table("skins")
    op.drop_table("particles")
    op.drop_table("logs")
    op.drop_table("effects")
    op.drop_table("backgrounds")
    op.drop_table("announces")
    op.drop_table("users")
    op.drop_table("genres")
    # ### end Alembic commands ###
