"""change field artists to subtitle

Revision ID: cc0b30214314
Revises: 75725650fd3c
Create Date: 2022-01-30 06:21:21.932712

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "cc0b30214314"
down_revision = "75725650fd3c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "backgrounds", sa.Column("subtitle", sa.String(length=128), nullable=True)
    )
    op.add_column(
        "backgrounds", sa.Column("subtitleEn", sa.String(length=128), nullable=True)
    )
    op.drop_column("backgrounds", "artistsEn")
    op.drop_column("backgrounds", "artists")
    op.add_column(
        "effects", sa.Column("subtitle", sa.String(length=128), nullable=True)
    )
    op.add_column(
        "effects", sa.Column("subtitleEn", sa.String(length=128), nullable=True)
    )
    op.drop_column("effects", "artistsEn")
    op.drop_column("effects", "artists")
    op.add_column(
        "engines", sa.Column("subtitle", sa.String(length=128), nullable=True)
    )
    op.add_column(
        "engines", sa.Column("subtitleEn", sa.String(length=128), nullable=True)
    )
    op.drop_column("engines", "artistsEn")
    op.drop_column("engines", "artists")
    op.add_column("levels", sa.Column("subtitle", sa.String(length=128), nullable=True))
    op.add_column(
        "levels", sa.Column("subtitleEn", sa.String(length=128), nullable=True)
    )
    op.drop_column("levels", "artistsEn")
    op.drop_column("levels", "artists")
    op.add_column(
        "particles", sa.Column("subtitle", sa.String(length=128), nullable=True)
    )
    op.add_column(
        "particles", sa.Column("subtitleEn", sa.String(length=128), nullable=True)
    )
    op.drop_column("particles", "artistsEn")
    op.drop_column("particles", "artists")
    op.add_column("skins", sa.Column("subtitle", sa.String(length=128), nullable=True))
    op.add_column(
        "skins", sa.Column("subtitleEn", sa.String(length=128), nullable=True)
    )
    op.drop_column("skins", "artistsEn")
    op.drop_column("skins", "artists")


def downgrade():
    op.add_column(
        "skins", sa.Column("artists", mysql.VARCHAR(length=128), nullable=True)
    )
    op.add_column(
        "skins", sa.Column("artistsEn", mysql.VARCHAR(length=128), nullable=True)
    )
    op.drop_column("skins", "subtitleEn")
    op.drop_column("skins", "subtitle")
    op.add_column(
        "particles", sa.Column("artists", mysql.VARCHAR(length=128), nullable=True)
    )
    op.add_column(
        "particles", sa.Column("artistsEn", mysql.VARCHAR(length=128), nullable=True)
    )
    op.drop_column("particles", "subtitleEn")
    op.drop_column("particles", "subtitle")
    op.add_column(
        "levels", sa.Column("artists", mysql.VARCHAR(length=128), nullable=True)
    )
    op.add_column(
        "levels", sa.Column("artistsEn", mysql.VARCHAR(length=128), nullable=True)
    )
    op.drop_column("levels", "subtitleEn")
    op.drop_column("levels", "subtitle")
    op.add_column(
        "engines", sa.Column("artists", mysql.VARCHAR(length=128), nullable=True)
    )
    op.add_column(
        "engines", sa.Column("artistsEn", mysql.VARCHAR(length=128), nullable=True)
    )
    op.drop_column("engines", "subtitleEn")
    op.drop_column("engines", "subtitle")
    op.add_column(
        "effects", sa.Column("artists", mysql.VARCHAR(length=128), nullable=True)
    )
    op.add_column(
        "effects", sa.Column("artistsEn", mysql.VARCHAR(length=128), nullable=True)
    )
    op.drop_column("effects", "subtitleEn")
    op.drop_column("effects", "subtitle")
    op.add_column(
        "backgrounds", sa.Column("artists", mysql.VARCHAR(length=128), nullable=True)
    )
    op.add_column(
        "backgrounds", sa.Column("artistsEn", mysql.VARCHAR(length=128), nullable=True)
    )
    op.drop_column("backgrounds", "subtitleEn")
    op.drop_column("backgrounds", "subtitle")
