# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from src.models.announce_resources import AnnounceResources


class Announce(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Announce - a model defined in OpenAPI

        announce_name: The announce_name of this Announce.
        title: The title of this Announce.
        subtitle: The subtitle of this Announce.
        date: The date of this Announce.
        body: The body of this Announce.
        resources: The resources of this Announce [Optional].
    """

    name: str
    title: str
    subtitle: str
    date: str
    body: str
    resources: Optional[AnnounceResources] = None


Announce.update_forward_refs()
