# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional, Union  # noqa: F401

from pydantic import BaseModel, validator
from src.models.sonolus_resource_locator import SonolusResourceLocator


class Background(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Background - a model defined in OpenAPI

        name: The name of this Background [Optional].
        version: The version of this Background [Optional].
        title: The title of this Background [Optional].
        titleEn: The titleEn of this Background [Optional].
        subtitle: The subtitle of this Background [Optional].
        subtitleEn: The subtitleEn of this Background [Optional].
        author: The author of this Background [Optional].
        authorEn: The authorEn of this Background [Optional].
        description: The description of this Background [Optional].
        descriptionEn: The descriptionEn of this Background [Optional].
        thumbnail: The thumbnail of this Background [Optional].
        data: The data of this Background [Optional].
        image: The image of this Background [Optional].
        configuration: The configuration of this Background [Optional].
        createdTime: The createdTime of this Background [Optional].
        updatedTime: The updatedTime of this Background [Optional].
        userId: The userId of this Background [Optional].
        public: The public of this Level [Optional].
    """

    class Config:
        orm_mode = True

    name: Optional[str] = None
    version: Optional[int] = None
    title: Optional[str] = None
    titleEn: Optional[str] = None
    subtitle: Optional[str] = None
    subtitleEn: Optional[str] = None
    author: Optional[str] = None
    authorEn: Optional[str] = None
    description: Optional[str] = None
    descriptionEn: Optional[str] = None
    thumbnail: Optional[SonolusResourceLocator] = None
    data: Optional[SonolusResourceLocator] = None
    image: Optional[SonolusResourceLocator] = None
    configuration: Optional[SonolusResourceLocator] = None
    createdTime: Optional[int] = None
    updatedTime: Optional[int] = None
    userId: Optional[str] = None
    public: Optional[bool] = None

    @validator("name")
    def name_min_length(cls, value):
        assert len(value) >= 1
        return value

    @validator("name")
    def name_max_length(cls, value):
        assert len(value) <= 50
        return value

    @validator("version")
    def version_max(cls, value):
        assert value <= 100
        return value

    @validator("version")
    def version_min(cls, value):
        assert value >= 1
        return value

    @validator("title")
    def title_min_length(cls, value):
        assert len(value) >= 1
        return value

    @validator("title")
    def title_max_length(cls, value):
        assert len(value) <= 100
        return value

    @validator("titleEn")
    def titleEn_max_length(cls, value):
        assert len(value) <= 100
        return value

    @validator("subtitle")
    def subtitle_min_length(cls, value):
        assert len(value) >= 1
        return value

    @validator("subtitle")
    def subtitle_max_length(cls, value):
        assert len(value) <= 100
        return value

    @validator("subtitleEn")
    def subtitleEn_max_length(cls, value):
        assert len(value) <= 100
        return value

    @validator("author")
    def author_min_length(cls, value):
        assert len(value) >= 1
        return value

    @validator("author")
    def author_max_length(cls, value):
        assert len(value) <= 50
        return value

    @validator("authorEn")
    def authorEn_max_length(cls, value):
        assert len(value) <= 50
        return value

    @validator("description")
    def description_min_length(cls, value):
        assert len(value) >= 0
        return value

    @validator("description")
    def description_max_length(cls, value):
        assert len(value) <= 3000
        return value

    @validator("descriptionEn")
    def descriptionEn_max_length(cls, value):
        assert len(value) <= 3000
        return value

    @validator("createdTime")
    def createdTime_min(cls, value):
        assert value >= 0
        return value

    @validator("updatedTime")
    def updatedTime_min(cls, value):
        assert value >= 0
        return value

    @validator("userId")
    def userId_min_length(cls, value):
        assert len(value) >= 1
        return value

    @validator("userId")
    def userId_max_length(cls, value):
        assert len(value) <= 100
        return value


Background.update_forward_refs()
