# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class EditAnnounceRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    EditAnnounceRequest - a model defined in OpenAPI

        name: The name of this EditAnnounceRequest [Optional].
        rating: The rating of this EditAnnounceRequest [Optional].
        title: The title of this EditAnnounceRequest [Optional].
        titleEn: The titleEn of this EditAnnounceRequest [Optional].
        subtitle: The subtitle of this EditAnnounceRequest [Optional].
        subtitleEn: The subtitleEn of this EditAnnounceRequest [Optional].
        author: The author of this EditAnnounceRequest [Optional].
        authorEn: The authorEn of this EditAnnounceRequest [Optional].
        description: The description of this EditAnnounceRequest [Optional].
        descriptionEn: The descriptionEn of this EditAnnounceRequest [Optional].
        cover: The cover of this EditAnnounceRequest [Optional].
        bgm: The bgm of this EditAnnounceRequest [Optional].
        preview: The preview of this EditAnnounceRequest [Optional].
        public: The public of this EditAnnounceRequest [Optional].
    """

    name: Optional[str] = None
    rating: Optional[int] = None
    title: Optional[str] = None
    titleEn: Optional[str] = None
    subtitle: Optional[str] = None
    subtitleEn: Optional[str] = None
    author: Optional[str] = None
    authorEn: Optional[str] = None
    description: Optional[str] = None
    descriptionEn: Optional[str] = None
    cover: Optional[str] = None
    bgm: Optional[str] = None
    preview: Optional[str] = None
    public: Optional[bool] = None

    @validator("name")
    def name_min_length(cls, value):
        assert len(value) >= 1
        return value

    @validator("name")
    def name_max_length(cls, value):
        assert len(value) <= 100
        return value

    @validator("rating")
    def rating_max(cls, value):
        assert value <= 100
        return value

    @validator("rating")
    def rating_min(cls, value):
        assert value >= 1
        return value

    @validator("title")
    def title_min_length(cls, value):
        assert len(value) >= 1
        return value

    @validator("title")
    def title_max_length(cls, value):
        assert len(value) <= 100
        return value

    @validator("titleEn")
    def titleEn_max_length(cls, value):
        assert len(value) <= 100
        return value

    @validator("subtitle")
    def subtitle_min_length(cls, value):
        assert len(value) >= 1
        return value

    @validator("subtitle")
    def subtitle_max_length(cls, value):
        assert len(value) <= 100
        return value

    @validator("subtitleEn")
    def subtitleEn_max_length(cls, value):
        assert len(value) <= 100
        return value

    @validator("author")
    def author_min_length(cls, value):
        assert len(value) >= 1
        return value

    @validator("author")
    def author_max_length(cls, value):
        assert len(value) <= 50
        return value

    @validator("authorEn")
    def authorEn_max_length(cls, value):
        assert len(value) <= 50
        return value

    @validator("description")
    def description_max_length(cls, value):
        assert len(value) <= 3000
        return value

    @validator("descriptionEn")
    def descriptionEn_max_length(cls, value):
        assert len(value) <= 3000
        return value


EditAnnounceRequest.update_forward_refs()
