# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class EditBackgroundRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    EditBackgroundRequest - a model defined in OpenAPI

        title: The title of this EditBackgroundRequest [Optional].
        title_en: The title_en of this EditBackgroundRequest [Optional].
        subtitle: The subtitle of this EditBackgroundRequest [Optional].
        subtitle_en: The subtitle_en of this EditBackgroundRequest [Optional].
        author: The author of this EditBackgroundRequest [Optional].
        author_en: The author_en of this EditBackgroundRequest [Optional].
        description: The description of this EditBackgroundRequest [Optional].
        description_en: The description_en of this EditBackgroundRequest [Optional].
        thumbnail: The thumbnail of this EditBackgroundRequest [Optional].
        data: The data of this EditBackgroundRequest [Optional].
        image: The image of this EditBackgroundRequest [Optional].
        configuration: The configuration of this EditBackgroundRequest [Optional].
    """

    title: Optional[str] = None
    title_en: Optional[str] = None
    subtitle: Optional[str] = None
    subtitle_en: Optional[str] = None
    author: Optional[str] = None
    author_en: Optional[str] = None
    description: Optional[str] = None
    description_en: Optional[str] = None
    thumbnail: Optional[str] = None
    data: Optional[str] = None
    image: Optional[str] = None
    configuration: Optional[str] = None

    @validator("title")
    def title_min_length(cls, value):
        assert len(value) >= 1
        return value

    @validator("title")
    def title_max_length(cls, value):
        assert len(value) <= 100
        return value

    @validator("title_en")
    def title_en_max_length(cls, value):
        assert len(value) <= 100
        return value

    @validator("subtitle")
    def subtitle_min_length(cls, value):
        assert len(value) >= 1
        return value

    @validator("subtitle")
    def subtitle_max_length(cls, value):
        assert len(value) <= 100
        return value

    @validator("subtitle_en")
    def subtitle_en_max_length(cls, value):
        assert len(value) <= 100
        return value

    @validator("author")
    def author_min_length(cls, value):
        assert len(value) >= 1
        return value

    @validator("author")
    def author_max_length(cls, value):
        assert len(value) <= 50
        return value

    @validator("author_en")
    def author_en_max_length(cls, value):
        assert len(value) <= 50
        return value

    @validator("description")
    def description_max_length(cls, value):
        assert len(value) <= 3000
        return value

    @validator("description_en")
    def description_en_max_length(cls, value):
        assert len(value) <= 3000
        return value

EditBackgroundRequest.update_forward_refs()
