# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from src.models.engine import Engine


class GetEngineResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    GetEngineResponse - a model defined in OpenAPI

        item: The item of this GetEngineResponse.
        description: The description of this GetEngineResponse.
        recommended: The recommended of this GetEngineResponse.
    """

    item: Engine
    description: str
    recommended: List[Engine]

    @validator("description")
    def description_min_length(cls, value):
        assert len(value) >= 1
        return value


GetEngineResponse.update_forward_refs()
