# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from src.models.user import User


class GetUserListResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    GetUserListResponse - a model defined in OpenAPI

        users: The users of this GetUserListResponse.
        total: The total of this GetUserListResponse.
        pages: The pages of this GetUserListResponse.
    """

    users: List[User]
    total: int
    pages: int


GetUserListResponse.update_forward_refs()
