# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from src.models.background import Background


class GetBackgroundResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    GetBackgroundResponse - a model defined in OpenAPI

        item: The item of this GetBackgroundResponse.
        description: The description of this GetBackgroundResponse.
        recommended: The recommended of this GetBackgroundResponse.
    """

    item: Background
    description: str
    recommended: List[Background]

    @validator("description")
    def description_min_length(cls, value):
        assert len(value) >= 1
        return value


GetBackgroundResponse.update_forward_refs()
