# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from src.models.particle import Particle


class GetParticleListResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    GetParticleListResponse - a model defined in OpenAPI

        page_count: The page_count of this GetParticleListResponse.
        items: The items of this GetParticleListResponse.
    """

    page_count: int
    items: List[Particle]

    @validator("page_count")
    def page_count_min(cls, value):
        assert value >= 1
        return value


GetParticleListResponse.update_forward_refs()
