# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from src.models.effect import Effect


class LevelUseEffect(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    LevelUseEffect - a model defined in OpenAPI

        use_default: The use_default of this LevelUseEffect [Optional].
        item: The item of this LevelUseEffect [Optional].
    """

    use_default: Optional[bool] = None
    item: Optional[Effect] = None


LevelUseEffect.update_forward_refs()
