# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from src.models.particle import Particle


class LevelUseParticle(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    LevelUseParticle - a model defined in OpenAPI

        useDefault: The use_default of this LevelUseParticle [Optional].
        item: The item of this LevelUseParticle [Optional].
    """

    useDefault: Optional[bool] = None
    item: Optional[Particle] = None


LevelUseParticle.update_forward_refs()
