# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class PostUploadResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    PostUploadResponse - a model defined in OpenAPI

        message: The message of this PostUploadResponse.
        filename: The filename of this PostUploadResponse [Optional].
    """

    message: str
    filename: Optional[str] = None


PostUploadResponse.update_forward_refs()
