# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class SearchToggleOption(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    SearchToggleOption - a model defined in OpenAPI

        query: The query of this SearchToggleOption.
        name: The name of this SearchToggleOption.
        type: The type of this SearchToggleOption.
        def: The default of this SearchToggleOption.
    """

    query: str
    name: str
    type: str
    default: int = Field(..., alias="def")

    @validator("default")
    def default_max(cls, value):
        assert value <= 1
        return value

    @validator("default")
    def default_min(cls, value):
        assert value >= 0
        return value


SearchToggleOption.update_forward_refs()
