# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from src.models.any_of_search_text_option_search_slider_option_search_toggle_option_search_select_option import (
    AnyOfSearchTextOptionSearchSliderOptionSearchToggleOptionSearchSelectOption,
)


class Search(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Search - a model defined in OpenAPI

        options: The options of this Search [Optional].
    """

    options: Optional[
        List[
            AnyOfSearchTextOptionSearchSliderOptionSearchToggleOptionSearchSelectOption
        ]
    ] = None


Search.update_forward_refs()
