# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401
from typing import Union

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from src.models.search_text_option import SearchTextOption
from src.models.search_slider_option import SearchSliderOption
from src.models.search_toggle_option import SearchToggleOption
from src.models.search_select_option import SearchSelectOption


class Search(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Search - a model defined in OpenAPI

        options: The options of this Search [Optional].
    """

    options: Optional[
        List[
            Union[
                SearchTextOption,
                SearchSliderOption,
                SearchSelectOption,
                SearchToggleOption,
            ]
        ]
    ] = None


Search.update_forward_refs()
