# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from src.models.effect import Effect
from src.models.search import Search


class ServerInfoEffects(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ServerInfoEffects - a model defined in OpenAPI

        items: The items of this ServerInfoEffects.
        search: The search of this ServerInfoEffects.
    """

    items: List[Effect]
    search: Search


ServerInfoEffects.update_forward_refs()
