# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from src.models.engine import Engine
from src.models.search import Search


class ServerInfoEngines(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ServerInfoEngines - a model defined in OpenAPI

        items: The items of this ServerInfoEngines.
        search: The search of this ServerInfoEngines.
    """

    items: List[Engine]
    search: Search


ServerInfoEngines.update_forward_refs()
