# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from src.models.background import Background
from src.models.effect import Effect
from src.models.engine import Engine
from src.models.level import Level
from src.models.particle import Particle
from src.models.skin import Skin


class ServerInfo(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ServerInfo - a model defined in OpenAPI

        levels: The levels of this ServerInfo.
        skins: The skins of this ServerInfo.
        backgrounds: The backgrounds of this ServerInfo.
        effects: The effects of this ServerInfo.
        particles: The particles of this ServerInfo.
        engines: The engines of this ServerInfo.
    """

    levels: List[Level]
    skins: List[Skin]
    backgrounds: List[Background]
    effects: List[Effect]
    particles: List[Particle]
    engines: List[Engine]


ServerInfo.update_forward_refs()
