# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from src.models.server_info_backgrounds import ServerInfoBackgrounds
from src.models.server_info_effects import ServerInfoEffects
from src.models.server_info_engines import ServerInfoEngines
from src.models.server_info_levels import ServerInfoLevels
from src.models.server_info_particles import ServerInfoParticles
from src.models.server_info_skins import ServerInfoSkins


class ServerInfo(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ServerInfo - a model defined in OpenAPI

        levels: The levels of this ServerInfo.
        skins: The skins of this ServerInfo.
        backgrounds: The backgrounds of this ServerInfo.
        effects: The effects of this ServerInfo.
        particles: The particles of this ServerInfo.
        engines: The engines of this ServerInfo.
    """

    levels: ServerInfoLevels
    skins: ServerInfoSkins
    backgrounds: ServerInfoBackgrounds
    effects: ServerInfoEffects
    particles: ServerInfoParticles
    engines: ServerInfoEngines


ServerInfo.update_forward_refs()
