# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from src.models.search import Search
from src.models.skin import Skin


class ServerInfoSkins(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ServerInfoSkins - a model defined in OpenAPI

        items: The items of this ServerInfoSkins.
        search: The search of this ServerInfoSkins.
    """

    items: List[Skin]
    search: Search


ServerInfoSkins.update_forward_refs()
