# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from src.models.particle import Particle
from src.models.search import Search


class ServerInfoParticles(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ServerInfoParticles - a model defined in OpenAPI

        items: The items of this ServerInfoParticles.
        search: The search of this ServerInfoParticles.
    """

    items: List[Particle]
    search: Search


ServerInfoParticles.update_forward_refs()
