# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from src.models.user_total_publish import UserTotalPublish


class UserTotal(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    UserTotal - a model defined in OpenAPI

        likes: The likes of this UserTotal [Optional].
        plays: The plays of this UserTotal [Optional].
        favorites: The favorites of this UserTotal [Optional].
        publish: The publish of this UserTotal [Optional].
    """

    likes: Optional[int] = None
    plays: Optional[int] = None
    favorites: Optional[int] = None
    publish: Optional[UserTotalPublish] = None

    @validator("likes")
    def likes_max(cls, value):
        assert value <= 10000000
        return value

    @validator("likes")
    def likes_min(cls, value):
        assert value >= 0
        return value

    @validator("plays")
    def plays_max(cls, value):
        assert value <= 10000000
        return value

    @validator("plays")
    def plays_min(cls, value):
        assert value >= 0
        return value

    @validator("favorites")
    def favorites_max(cls, value):
        assert value <= 10000000
        return value

    @validator("favorites")
    def favorites_min(cls, value):
        assert value >= 0
        return value


UserTotal.update_forward_refs()
