# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from src.models.user_total import UserTotal


class User(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    User - a model defined in OpenAPI

        userId: The userId of this User [Optional].
        testId: The testId of this User [Optional].
        accountId: The accountId of this User [Optional].
        description: The description of this User [Optional].
        createdTime: The createdTime of this User [Optional].
        updatedTime: The updatedTime of this User [Optional].
        total: The total of this User [Optional].
        isAdmin: The isAdmin of this User [Optional].
        isDeleted: The isDeleted of this User [Optional].
    """

    userId: Optional[str] = None
    testId: Optional[str] = None
    accountId: Optional[str] = None
    description: Optional[str] = None
    createdTime: Optional[int] = None
    updatedTime: Optional[int] = None
    total: Optional[UserTotal] = None
    isAdmin: Optional[bool] = None
    isDeleted: Optional[bool] = None

    @validator("userId")
    def userId_min_length(cls, value):
        assert len(value) >= 1
        return value

    @validator("userId")
    def userId_max_length(cls, value):
        assert len(value) <= 30
        return value

    @validator("testId")
    def testId_min_length(cls, value):
        assert len(value) >= 8
        return value

    @validator("testId")
    def testId_max_length(cls, value):
        assert len(value) <= 8
        return value

    @validator("description")
    def description_min_length(cls, value):
        assert len(value) >= 1
        return value

    @validator("description")
    def description_max_length(cls, value):
        assert len(value) <= 3000
        return value

    @validator("createdTime")
    def createdTime_min(cls, value):
        assert value >= 0
        return value

    @validator("updatedTime")
    def updatedTime_min(cls, value):
        assert value >= 0
        return value


User.update_forward_refs()
