# coding: utf-8

"""
    SweetPotato Server 3 API

    Sonolusの基本APIを大幅に捻じ曲げるサーバー
    フロントエンド専用のエンドポイントは一切持たず
    マイリストなどを含め全てのリクエストはSonolusアプリ内のリクエストと互換(つまり全部GETきっも)
     ユーザー認証は以前同様に FirebaseAuthorizationでなんとかする。
     (実際にはaccountKeyとかいう概念で認証をスキップできちゃうが...まぁゲームだしええやろ)
     変更点: /levels/{levelName} へのPOST を /levels に変更、一般的ではないエンドポイントだったので

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI
from src.apis.accounts_api import router as AccountsApiRouter
from src.apis.announces_api import router as AnnouncesApiRouter
from src.apis.backgrounds_api import router as BackgroundsApiRouter
from src.apis.effects_api import router as EffectsApiRouter
from src.apis.engines_api import router as EnginesApiRouter
from src.apis.info_api import router as InfoApiRouter
from src.apis.levels_api import router as LevelsApiRouter
from src.apis.particles_api import router as ParticlesApiRouter
from src.apis.pickups_api import router as PickupsApiRouter
from src.apis.skins_api import router as SkinsApiRouter
from src.apis.tests_api import router as TestsApiRouter
from src.apis.users_api import router as UsersApiRouter

app = FastAPI(
    title="SweetPotato Server 3 API",
    description="Sonolusの基本APIを大幅に捻じ曲げたサーバー",
    version="1.0",
)

app.include_router(AccountsApiRouter)
app.include_router(AnnouncesApiRouter)
app.include_router(BackgroundsApiRouter)
app.include_router(EffectsApiRouter)
app.include_router(EnginesApiRouter)
app.include_router(InfoApiRouter)
app.include_router(LevelsApiRouter)
app.include_router(ParticlesApiRouter)
app.include_router(PickupsApiRouter)
app.include_router(SkinsApiRouter)
app.include_router(TestsApiRouter)
app.include_router(UsersApiRouter)
